// Интерфейс на 29 языках. Язык выбирается по настройкам телефона.

const K = [
  'appName', 'me', 'partner', 'tapMic', 'worksOffline', 'listening', 'done', 'cancel', 'recognizing',
  'translating', 'typeHere', 'noSpeech', 'notUnderstood', 'micDenied', 'prepareTitle', 'prepareText',
  'download', 'downloading', 'readyOffline', 'settings', 'uiLanguage', 'auto', 'autoSpeak', 'slowSpeech',
  'recognition', 'fast', 'accurate', 'faceMode', 'clearHistory', 'installTitle', 'installIOS',
  'installAndroid', 'noVoice', 'notDownloaded', 'error', 'close', 'myLanguage', 'partnerLanguage',
  'copied', 'loading',
];

// Порядок значений строго как в K
const T = {
  en: ['Translator', 'Me', 'Partner', 'Tap the microphone and speak', 'Works without internet after download', 'Listening…', 'Done', 'Cancel', 'Recognizing…', 'Translating…', 'Type text…', 'No speech heard — please try again', "Didn't catch that — please repeat", 'Please allow microphone access', 'Download for offline use', 'Speech recognition and translation for this language pair will be saved on your device. After that, everything works without internet.', 'Download', 'Downloading…', 'Ready offline', 'Settings', 'Interface language', 'Automatic', 'Speak translation aloud', 'Slow speech', 'Speech recognition', 'Fast', 'Accurate', 'Face-to-face mode', 'Clear history', 'Install the app', 'Tap Share, then “Add to Home Screen”', 'Open the browser menu and tap “Install app”', 'No voice for this language on this device', 'Not downloaded yet — connect to the internet once and tap Download', 'Something went wrong — please try again', 'Close', 'My language', "Partner's language", 'Copied', 'Loading…'],
  ru: ['Переводчик', 'Я', 'Собеседник', 'Нажмите на микрофон и говорите', 'После загрузки работает без интернета', 'Слушаю…', 'Готово', 'Отмена', 'Распознаю…', 'Перевожу…', 'Введите текст…', 'Не слышно речи — попробуйте ещё раз', 'Не разобрал — повторите, пожалуйста', 'Разрешите доступ к микрофону', 'Скачать для работы без интернета', 'Распознавание речи и перевод для этой пары языков сохранятся на устройстве. После этого всё работает без интернета.', 'Скачать', 'Скачивается…', 'Готово к работе без сети', 'Настройки', 'Язык интерфейса', 'Автоматически', 'Озвучивать перевод', 'Медленная речь', 'Распознавание речи', 'Быстрое', 'Точное', 'Режим «лицом к лицу»', 'Очистить историю', 'Установите приложение', 'Нажмите «Поделиться», затем «На экран „Домой“»', 'Откройте меню браузера и нажмите «Установить приложение»', 'На этом устройстве нет голоса для этого языка', 'Ещё не скачано — подключитесь к интернету один раз и нажмите «Скачать»', 'Что-то пошло не так — попробуйте ещё раз', 'Закрыть', 'Мой язык', 'Язык собеседника', 'Скопировано', 'Загрузка…'],
  fi: ['Kääntäjä', 'Minä', 'Keskustelija', 'Napauta mikrofonia ja puhu', 'Toimii ilman internetiä latauksen jälkeen', 'Kuuntelen…', 'Valmis', 'Peruuta', 'Tunnistan…', 'Käännän…', 'Kirjoita tekstiä…', 'Puhetta ei kuulunut — yritä uudelleen', 'En saanut selvää — toista, kiitos', 'Salli mikrofonin käyttö', 'Lataa offline-käyttöä varten', 'Puheentunnistus ja käännös tälle kieliparille tallennetaan laitteellesi. Sen jälkeen kaikki toimii ilman internetiä.', 'Lataa', 'Ladataan…', 'Valmis offline-käyttöön', 'Asetukset', 'Käyttöliittymän kieli', 'Automaattinen', 'Lue käännös ääneen', 'Hidas puhe', 'Puheentunnistus', 'Nopea', 'Tarkka', 'Kasvokkain-tila', 'Tyhjennä historia', 'Asenna sovellus', 'Napauta Jaa ja sitten ”Lisää Koti-valikkoon”', 'Avaa selaimen valikko ja napauta ”Asenna sovellus”', 'Tälle kielelle ei ole ääntä tässä laitteessa', 'Ei vielä ladattu — yhdistä internetiin kerran ja napauta Lataa', 'Jokin meni pieleen — yritä uudelleen', 'Sulje', 'Minun kieleni', 'Keskustelijan kieli', 'Kopioitu', 'Ladataan…'],
  bg: ['Преводач', 'Аз', 'Събеседник', 'Натиснете микрофона и говорете', 'След изтегляне работи без интернет', 'Слушам…', 'Готово', 'Отказ', 'Разпознавам…', 'Превеждам…', 'Въведете текст…', 'Не се чува реч — опитайте отново', 'Не разбрах — повторете, моля', 'Разрешете достъп до микрофона', 'Изтегляне за работа без интернет', 'Разпознаването на реч и преводът за тази езикова двойка ще се запазят на устройството. След това всичко работи без интернет.', 'Изтегли', 'Изтегля се…', 'Готово за работа без мрежа', 'Настройки', 'Език на интерфейса', 'Автоматично', 'Озвучаване на превода', 'Бавна реч', 'Разпознаване на реч', 'Бързо', 'Точно', 'Режим „лице в лице“', 'Изчисти историята', 'Инсталирайте приложението', 'Натиснете „Сподели“, после „Добави към началния екран“', 'Отворете менюто на браузъра и натиснете „Инсталиране на приложението“', 'На това устройство няма глас за този език', 'Още не е изтеглено — свържете се с интернет веднъж и натиснете „Изтегли“', 'Нещо се обърка — опитайте отново', 'Затвори', 'Моят език', 'Език на събеседника', 'Копирано', 'Зареждане…'],
  uk: ['Перекладач', 'Я', 'Співрозмовник', 'Натисніть на мікрофон і говоріть', 'Після завантаження працює без інтернету', 'Слухаю…', 'Готово', 'Скасувати', 'Розпізнаю…', 'Перекладаю…', 'Введіть текст…', 'Не чути мовлення — спробуйте ще раз', 'Не розібрав — повторіть, будь ласка', 'Дозвольте доступ до мікрофона', 'Завантажити для роботи без інтернету', 'Розпізнавання мовлення і переклад для цієї пари мов збережуться на пристрої. Після цього все працює без інтернету.', 'Завантажити', 'Завантажується…', 'Готово до роботи без мережі', 'Налаштування', 'Мова інтерфейсу', 'Автоматично', 'Озвучувати переклад', 'Повільне мовлення', 'Розпізнавання мовлення', 'Швидке', 'Точне', 'Режим «віч-на-віч»', 'Очистити історію', 'Встановіть застосунок', 'Натисніть «Поділитися», потім «На екран „Додому“»', 'Відкрийте меню браузера й натисніть «Встановити застосунок»', 'На цьому пристрої немає голосу для цієї мови', 'Ще не завантажено — підключіться до інтернету один раз і натисніть «Завантажити»', 'Щось пішло не так — спробуйте ще раз', 'Закрити', 'Моя мова', 'Мова співрозмовника', 'Скопійовано', 'Завантаження…'],
  et: ['Tõlkija', 'Mina', 'Vestluskaaslane', 'Puuduta mikrofoni ja räägi', 'Pärast allalaadimist töötab ilma internetita', 'Kuulan…', 'Valmis', 'Tühista', 'Tuvastan…', 'Tõlgin…', 'Sisesta tekst…', 'Kõnet ei kuulnud — proovi uuesti', 'Ei saanud aru — korda palun', 'Luba mikrofoni kasutamine', 'Laadi alla võrguühenduseta kasutuseks', 'Selle keelepaari kõnetuvastus ja tõlge salvestatakse sinu seadmesse. Pärast seda töötab kõik ilma internetita.', 'Laadi alla', 'Laadin alla…', 'Valmis võrguta tööks', 'Seaded', 'Liidese keel', 'Automaatne', 'Loe tõlge ette', 'Aeglane kõne', 'Kõnetuvastus', 'Kiire', 'Täpne', 'Näost näkku režiim', 'Tühjenda ajalugu', 'Paigalda rakendus', 'Puuduta Jaga ja seejärel „Lisa avakuvale“', 'Ava brauseri menüü ja puuduta „Installi rakendus“', 'Selles seadmes pole selle keele häält', 'Pole veel alla laaditud — ühenda korra internetti ja puuduta Laadi alla', 'Midagi läks valesti — proovi uuesti', 'Sulge', 'Minu keel', 'Vestluskaaslase keel', 'Kopeeritud', 'Laadin…'],
  sv: ['Översättare', 'Jag', 'Samtalspartner', 'Tryck på mikrofonen och tala', 'Fungerar utan internet efter nedladdning', 'Lyssnar…', 'Klar', 'Avbryt', 'Känner igen…', 'Översätter…', 'Skriv text…', 'Inget tal hördes — försök igen', 'Uppfattade inte — upprepa, tack', 'Tillåt åtkomst till mikrofonen', 'Ladda ner för offlineanvändning', 'Taligenkänning och översättning för detta språkpar sparas på enheten. Därefter fungerar allt utan internet.', 'Ladda ner', 'Laddar ner…', 'Redo offline', 'Inställningar', 'Gränssnittsspråk', 'Automatiskt', 'Läs upp översättningen', 'Långsamt tal', 'Taligenkänning', 'Snabb', 'Noggrann', 'Ansikte mot ansikte', 'Rensa historik', 'Installera appen', 'Tryck på Dela och sedan ”Lägg till på hemskärmen”', 'Öppna webbläsarens meny och tryck på ”Installera app”', 'Ingen röst för detta språk på enheten', 'Inte nedladdat än — anslut till internet en gång och tryck på Ladda ner', 'Något gick fel — försök igen', 'Stäng', 'Mitt språk', 'Samtalspartnerns språk', 'Kopierat', 'Laddar…'],
  de: ['Übersetzer', 'Ich', 'Gegenüber', 'Tippe auf das Mikrofon und sprich', 'Funktioniert nach dem Download ohne Internet', 'Ich höre zu…', 'Fertig', 'Abbrechen', 'Erkenne…', 'Übersetze…', 'Text eingeben…', 'Keine Sprache erkannt — bitte erneut versuchen', 'Nicht verstanden — bitte wiederholen', 'Bitte Mikrofonzugriff erlauben', 'Für die Offline-Nutzung herunterladen', 'Spracherkennung und Übersetzung für dieses Sprachpaar werden auf dem Gerät gespeichert. Danach funktioniert alles ohne Internet.', 'Herunterladen', 'Wird heruntergeladen…', 'Offline bereit', 'Einstellungen', 'Sprache der Oberfläche', 'Automatisch', 'Übersetzung vorlesen', 'Langsame Sprache', 'Spracherkennung', 'Schnell', 'Genau', 'Gesicht-zu-Gesicht-Modus', 'Verlauf löschen', 'App installieren', 'Tippe auf Teilen und dann auf „Zum Home-Bildschirm“', 'Öffne das Browsermenü und tippe auf „App installieren“', 'Keine Stimme für diese Sprache auf diesem Gerät', 'Noch nicht heruntergeladen — einmal mit dem Internet verbinden und auf Herunterladen tippen', 'Etwas ist schiefgelaufen — bitte erneut versuchen', 'Schließen', 'Meine Sprache', 'Sprache des Gegenübers', 'Kopiert', 'Lädt…'],
  es: ['Traductor', 'Yo', 'Interlocutor', 'Toca el micrófono y habla', 'Funciona sin internet después de descargar', 'Escuchando…', 'Listo', 'Cancelar', 'Reconociendo…', 'Traduciendo…', 'Escribe un texto…', 'No se oyó nada — inténtalo de nuevo', 'No te entendí — repite, por favor', 'Permite el acceso al micrófono', 'Descargar para usar sin conexión', 'El reconocimiento de voz y la traducción de este par de idiomas se guardarán en tu dispositivo. Después todo funciona sin internet.', 'Descargar', 'Descargando…', 'Listo sin conexión', 'Ajustes', 'Idioma de la interfaz', 'Automático', 'Leer la traducción en voz alta', 'Habla lenta', 'Reconocimiento de voz', 'Rápido', 'Preciso', 'Modo cara a cara', 'Borrar historial', 'Instala la app', 'Toca Compartir y luego «Añadir a pantalla de inicio»', 'Abre el menú del navegador y toca «Instalar aplicación»', 'No hay voz para este idioma en este dispositivo', 'Aún no se ha descargado — conéctate a internet una vez y toca Descargar', 'Algo salió mal — inténtalo de nuevo', 'Cerrar', 'Mi idioma', 'Idioma del interlocutor', 'Copiado', 'Cargando…'],
  fr: ['Traducteur', 'Moi', 'Interlocuteur', 'Touchez le micro et parlez', 'Fonctionne sans internet après le téléchargement', 'J’écoute…', 'Terminé', 'Annuler', 'Reconnaissance…', 'Traduction…', 'Saisissez un texte…', 'Aucune voix détectée — réessayez', 'Je n’ai pas compris — répétez, s’il vous plaît', 'Autorisez l’accès au micro', 'Télécharger pour une utilisation hors ligne', 'La reconnaissance vocale et la traduction pour cette paire de langues seront enregistrées sur l’appareil. Ensuite, tout fonctionne sans internet.', 'Télécharger', 'Téléchargement…', 'Prêt hors ligne', 'Réglages', 'Langue de l’interface', 'Automatique', 'Lire la traduction à voix haute', 'Parole lente', 'Reconnaissance vocale', 'Rapide', 'Précise', 'Mode face à face', 'Effacer l’historique', 'Installez l’app', 'Touchez Partager, puis « Sur l’écran d’accueil »', 'Ouvrez le menu du navigateur et touchez « Installer l’application »', 'Aucune voix pour cette langue sur cet appareil', 'Pas encore téléchargé — connectez-vous une fois à internet et touchez Télécharger', 'Un problème est survenu — réessayez', 'Fermer', 'Ma langue', 'Langue de l’interlocuteur', 'Copié', 'Chargement…'],
  it: ['Traduttore', 'Io', 'Interlocutore', 'Tocca il microfono e parla', 'Funziona senza internet dopo il download', 'Ascolto…', 'Fatto', 'Annulla', 'Riconoscimento…', 'Traduzione…', 'Scrivi un testo…', 'Nessuna voce rilevata — riprova', 'Non ho capito — ripeti, per favore', 'Consenti l’accesso al microfono', 'Scarica per l’uso offline', 'Il riconoscimento vocale e la traduzione per questa coppia di lingue verranno salvati sul dispositivo. Dopo, tutto funziona senza internet.', 'Scarica', 'Download in corso…', 'Pronto offline', 'Impostazioni', 'Lingua dell’interfaccia', 'Automatica', 'Leggi la traduzione ad alta voce', 'Voce lenta', 'Riconoscimento vocale', 'Veloce', 'Preciso', 'Modalità faccia a faccia', 'Cancella cronologia', 'Installa l’app', 'Tocca Condividi, poi «Aggiungi alla schermata Home»', 'Apri il menu del browser e tocca «Installa app»', 'Nessuna voce per questa lingua su questo dispositivo', 'Non ancora scaricato — connettiti a internet una volta e tocca Scarica', 'Qualcosa è andato storto — riprova', 'Chiudi', 'La mia lingua', 'Lingua dell’interlocutore', 'Copiato', 'Caricamento…'],
  pt: ['Tradutor', 'Eu', 'Interlocutor', 'Toque no microfone e fale', 'Funciona sem internet após o download', 'Ouvindo…', 'Pronto', 'Cancelar', 'Reconhecendo…', 'Traduzindo…', 'Digite um texto…', 'Nenhuma fala detectada — tente novamente', 'Não entendi — repita, por favor', 'Permita o acesso ao microfone', 'Baixar para usar offline', 'O reconhecimento de voz e a tradução deste par de idiomas serão salvos no seu dispositivo. Depois disso, tudo funciona sem internet.', 'Baixar', 'Baixando…', 'Pronto para uso offline', 'Ajustes', 'Idioma da interface', 'Automático', 'Ler a tradução em voz alta', 'Fala lenta', 'Reconhecimento de voz', 'Rápido', 'Preciso', 'Modo frente a frente', 'Limpar histórico', 'Instale o app', 'Toque em Compartilhar e depois em “Adicionar à Tela de Início”', 'Abra o menu do navegador e toque em “Instalar app”', 'Não há voz para este idioma neste dispositivo', 'Ainda não baixado — conecte-se à internet uma vez e toque em Baixar', 'Algo deu errado — tente novamente', 'Fechar', 'Meu idioma', 'Idioma do interlocutor', 'Copiado', 'Carregando…'],
  pl: ['Tłumacz', 'Ja', 'Rozmówca', 'Dotknij mikrofonu i mów', 'Po pobraniu działa bez internetu', 'Słucham…', 'Gotowe', 'Anuluj', 'Rozpoznaję…', 'Tłumaczę…', 'Wpisz tekst…', 'Nie słychać mowy — spróbuj ponownie', 'Nie zrozumiałem — powtórz, proszę', 'Zezwól na dostęp do mikrofonu', 'Pobierz do użytku offline', 'Rozpoznawanie mowy i tłumaczenie dla tej pary języków zostaną zapisane na urządzeniu. Potem wszystko działa bez internetu.', 'Pobierz', 'Pobieranie…', 'Gotowe do pracy offline', 'Ustawienia', 'Język interfejsu', 'Automatycznie', 'Czytaj tłumaczenie na głos', 'Wolna mowa', 'Rozpoznawanie mowy', 'Szybkie', 'Dokładne', 'Tryb twarzą w twarz', 'Wyczyść historię', 'Zainstaluj aplikację', 'Stuknij Udostępnij, a potem „Do ekranu początkowego”', 'Otwórz menu przeglądarki i stuknij „Zainstaluj aplikację”', 'Brak głosu dla tego języka na tym urządzeniu', 'Jeszcze nie pobrano — połącz się raz z internetem i stuknij Pobierz', 'Coś poszło nie tak — spróbuj ponownie', 'Zamknij', 'Mój język', 'Język rozmówcy', 'Skopiowano', 'Ładowanie…'],
  tr: ['Çevirmen', 'Ben', 'Karşı taraf', 'Mikrofona dokunun ve konuşun', 'İndirdikten sonra internetsiz çalışır', 'Dinliyorum…', 'Tamam', 'İptal', 'Tanınıyor…', 'Çevriliyor…', 'Metin yazın…', 'Konuşma duyulmadı — tekrar deneyin', 'Anlayamadım — lütfen tekrarlayın', 'Lütfen mikrofon erişimine izin verin', 'Çevrimdışı kullanım için indir', 'Bu dil çifti için konuşma tanıma ve çeviri cihazınıza kaydedilecek. Ardından her şey internetsiz çalışır.', 'İndir', 'İndiriliyor…', 'Çevrimdışı hazır', 'Ayarlar', 'Arayüz dili', 'Otomatik', 'Çeviriyi sesli oku', 'Yavaş konuşma', 'Konuşma tanıma', 'Hızlı', 'Doğru', 'Yüz yüze modu', 'Geçmişi temizle', 'Uygulamayı yükleyin', 'Paylaş’a, ardından “Ana Ekrana Ekle”ye dokunun', 'Tarayıcı menüsünü açın ve “Uygulamayı yükle”ye dokunun', 'Bu cihazda bu dil için ses yok', 'Henüz indirilmedi — bir kez internete bağlanın ve İndir’e dokunun', 'Bir sorun oluştu — tekrar deneyin', 'Kapat', 'Benim dilim', 'Karşı tarafın dili', 'Kopyalandı', 'Yükleniyor…'],
  ar: ['المترجم', 'أنا', 'المحاور', 'اضغط على الميكروفون وتحدث', 'يعمل دون إنترنت بعد التنزيل', 'أستمع…', 'تم', 'إلغاء', 'جارٍ التعرّف…', 'جارٍ الترجمة…', 'اكتب نصًا…', 'لم يُسمع أي كلام — حاول مرة أخرى', 'لم أفهم — كرّر من فضلك', 'يُرجى السماح بالوصول إلى الميكروفون', 'تنزيل للاستخدام دون اتصال', 'سيتم حفظ التعرّف على الكلام والترجمة لهذين اللغتين على جهازك. بعد ذلك يعمل كل شيء دون إنترنت.', 'تنزيل', 'جارٍ التنزيل…', 'جاهز دون اتصال', 'الإعدادات', 'لغة الواجهة', 'تلقائي', 'قراءة الترجمة بصوت عالٍ', 'كلام بطيء', 'التعرّف على الكلام', 'سريع', 'دقيق', 'وضع وجهًا لوجه', 'مسح السجل', 'ثبّت التطبيق', 'اضغط على مشاركة، ثم «إضافة إلى الشاشة الرئيسية»', 'افتح قائمة المتصفح واضغط «تثبيت التطبيق»', 'لا يوجد صوت لهذه اللغة على هذا الجهاز', 'لم يتم التنزيل بعد — اتصل بالإنترنت مرة واحدة واضغط تنزيل', 'حدث خطأ ما — حاول مرة أخرى', 'إغلاق', 'لغتي', 'لغة المحاور', 'تم النسخ', 'جارٍ التحميل…'],
  zh: ['翻译', '我', '对方', '点击麦克风开始说话', '下载后无需网络即可使用', '正在聆听…', '完成', '取消', '正在识别…', '正在翻译…', '输入文字…', '没有听到声音，请重试', '没听清，请再说一遍', '请允许使用麦克风', '下载以便离线使用', '此语言对的语音识别和翻译将保存在您的设备上。之后无需网络即可使用全部功能。', '下载', '正在下载…', '可离线使用', '设置', '界面语言', '自动', '朗读译文', '慢速朗读', '语音识别', '快速', '精准', '面对面模式', '清除历史', '安装应用', '点击“分享”，然后选择“添加到主屏幕”', '打开浏览器菜单，点击“安装应用”', '此设备上没有该语言的语音', '尚未下载 — 请联网一次并点击“下载”', '出了点问题，请重试', '关闭', '我的语言', '对方的语言', '已复制', '加载中…'],
  ja: ['翻訳', '自分', '相手', 'マイクをタップして話してください', 'ダウンロード後はオフラインで使えます', '聞いています…', '完了', 'キャンセル', '認識中…', '翻訳中…', 'テキストを入力…', '音声が聞こえませんでした。もう一度お試しください', '聞き取れませんでした。もう一度お願いします', 'マイクへのアクセスを許可してください', 'オフライン用にダウンロード', 'この言語ペアの音声認識と翻訳がデバイスに保存されます。その後はインターネットなしで使えます。', 'ダウンロード', 'ダウンロード中…', 'オフラインで使用可能', '設定', '表示言語', '自動', '翻訳を読み上げる', 'ゆっくり読み上げ', '音声認識', '高速', '高精度', '対面モード', '履歴を消去', 'アプリをインストール', '共有をタップし、「ホーム画面に追加」を選んでください', 'ブラウザのメニューを開き、「アプリをインストール」をタップ', 'このデバイスにはこの言語の音声がありません', 'まだダウンロードされていません。一度インターネットに接続して「ダウンロード」をタップしてください', '問題が発生しました。もう一度お試しください', '閉じる', '自分の言語', '相手の言語', 'コピーしました', '読み込み中…'],
  ko: ['번역기', '나', '상대방', '마이크를 누르고 말하세요', '다운로드 후 인터넷 없이 작동합니다', '듣고 있어요…', '완료', '취소', '인식 중…', '번역 중…', '텍스트 입력…', '음성이 들리지 않았어요. 다시 시도하세요', '잘 못 들었어요. 다시 말씀해 주세요', '마이크 접근을 허용해 주세요', '오프라인용으로 다운로드', '이 언어 쌍의 음성 인식과 번역이 기기에 저장됩니다. 이후에는 인터넷 없이 모두 작동합니다.', '다운로드', '다운로드 중…', '오프라인 준비 완료', '설정', '인터페이스 언어', '자동', '번역 읽어 주기', '느린 말하기', '음성 인식', '빠름', '정확', '대면 모드', '기록 지우기', '앱 설치하기', '공유를 누른 다음 “홈 화면에 추가”를 선택하세요', '브라우저 메뉴를 열고 “앱 설치”를 누르세요', '이 기기에 이 언어의 음성이 없습니다', '아직 다운로드되지 않았어요. 인터넷에 한 번 연결한 후 다운로드를 누르세요', '문제가 발생했어요. 다시 시도하세요', '닫기', '내 언어', '상대방 언어', '복사됨', '불러오는 중…'],
  hi: ['अनुवादक', 'मैं', 'सामने वाला', 'माइक्रोफ़ोन दबाएँ और बोलें', 'डाउनलोड के बाद बिना इंटरनेट काम करता है', 'सुन रहा हूँ…', 'हो गया', 'रद्द करें', 'पहचान रहा हूँ…', 'अनुवाद हो रहा है…', 'टेक्स्ट लिखें…', 'कोई आवाज़ नहीं सुनाई दी — फिर से कोशिश करें', 'समझ नहीं आया — कृपया दोहराएँ', 'कृपया माइक्रोफ़ोन की अनुमति दें', 'ऑफ़लाइन उपयोग के लिए डाउनलोड करें', 'इस भाषा जोड़ी के लिए वाक् पहचान और अनुवाद आपके डिवाइस पर सहेजे जाएँगे। उसके बाद सब कुछ बिना इंटरनेट काम करता है।', 'डाउनलोड करें', 'डाउनलोड हो रहा है…', 'ऑफ़लाइन तैयार', 'सेटिंग्स', 'इंटरफ़ेस की भाषा', 'स्वचालित', 'अनुवाद बोलकर सुनाएँ', 'धीमी आवाज़', 'वाक् पहचान', 'तेज़', 'सटीक', 'आमने-सामने मोड', 'इतिहास मिटाएँ', 'ऐप इंस्टॉल करें', 'शेयर दबाएँ, फिर “होम स्क्रीन में जोड़ें” चुनें', 'ब्राउज़र मेनू खोलें और “ऐप इंस्टॉल करें” दबाएँ', 'इस डिवाइस पर इस भाषा की आवाज़ नहीं है', 'अभी डाउनलोड नहीं हुआ — एक बार इंटरनेट से जुड़ें और डाउनलोड दबाएँ', 'कुछ गलत हो गया — फिर से कोशिश करें', 'बंद करें', 'मेरी भाषा', 'सामने वाले की भाषा', 'कॉपी हो गया', 'लोड हो रहा है…'],
  nl: ['Vertaler', 'Ik', 'Gesprekspartner', 'Tik op de microfoon en spreek', 'Werkt na het downloaden zonder internet', 'Ik luister…', 'Klaar', 'Annuleren', 'Herkennen…', 'Vertalen…', 'Typ tekst…', 'Geen spraak gehoord — probeer het opnieuw', 'Niet verstaan — herhaal het alstublieft', 'Sta toegang tot de microfoon toe', 'Downloaden voor offline gebruik', 'Spraakherkenning en vertaling voor dit taalpaar worden op je apparaat opgeslagen. Daarna werkt alles zonder internet.', 'Downloaden', 'Downloaden…', 'Klaar voor offline gebruik', 'Instellingen', 'Taal van de interface', 'Automatisch', 'Vertaling voorlezen', 'Langzaam spreken', 'Spraakherkenning', 'Snel', 'Nauwkeurig', 'Gezicht-tot-gezicht-modus', 'Geschiedenis wissen', 'Installeer de app', 'Tik op Deel en daarna op ‘Zet op beginscherm’', 'Open het browsermenu en tik op ‘App installeren’', 'Geen stem voor deze taal op dit apparaat', 'Nog niet gedownload — maak één keer verbinding met internet en tik op Downloaden', 'Er ging iets mis — probeer het opnieuw', 'Sluiten', 'Mijn taal', 'Taal van gesprekspartner', 'Gekopieerd', 'Laden…'],
  el: ['Μεταφραστής', 'Εγώ', 'Συνομιλητής', 'Πατήστε το μικρόφωνο και μιλήστε', 'Λειτουργεί χωρίς ίντερνετ μετά τη λήψη', 'Ακούω…', 'Τέλος', 'Ακύρωση', 'Αναγνώριση…', 'Μετάφραση…', 'Γράψτε κείμενο…', 'Δεν ακούστηκε ομιλία — δοκιμάστε ξανά', 'Δεν κατάλαβα — επαναλάβετε, παρακαλώ', 'Επιτρέψτε την πρόσβαση στο μικρόφωνο', 'Λήψη για χρήση εκτός σύνδεσης', 'Η αναγνώριση ομιλίας και η μετάφραση για αυτό το ζεύγος γλωσσών θα αποθηκευτούν στη συσκευή σας. Μετά όλα λειτουργούν χωρίς ίντερνετ.', 'Λήψη', 'Γίνεται λήψη…', 'Έτοιμο εκτός σύνδεσης', 'Ρυθμίσεις', 'Γλώσσα διεπαφής', 'Αυτόματα', 'Ανάγνωση μετάφρασης', 'Αργή ομιλία', 'Αναγνώριση ομιλίας', 'Γρήγορη', 'Ακριβής', 'Λειτουργία πρόσωπο με πρόσωπο', 'Διαγραφή ιστορικού', 'Εγκαταστήστε την εφαρμογή', 'Πατήστε Κοινοποίηση και μετά «Προσθήκη στην οθόνη Αφετηρίας»', 'Ανοίξτε το μενού του προγράμματος περιήγησης και πατήστε «Εγκατάσταση εφαρμογής»', 'Δεν υπάρχει φωνή για αυτή τη γλώσσα σε αυτή τη συσκευή', 'Δεν έχει γίνει λήψη ακόμα — συνδεθείτε μία φορά στο ίντερνετ και πατήστε Λήψη', 'Κάτι πήγε στραβά — δοκιμάστε ξανά', 'Κλείσιμο', 'Η γλώσσα μου', 'Γλώσσα συνομιλητή', 'Αντιγράφηκε', 'Φόρτωση…'],
  ro: ['Traducător', 'Eu', 'Interlocutor', 'Atinge microfonul și vorbește', 'Funcționează fără internet după descărcare', 'Ascult…', 'Gata', 'Anulează', 'Recunosc…', 'Traduc…', 'Scrie un text…', 'Nu s-a auzit nimic — încearcă din nou', 'Nu am înțeles — repetă, te rog', 'Permite accesul la microfon', 'Descarcă pentru utilizare offline', 'Recunoașterea vocală și traducerea pentru această pereche de limbi vor fi salvate pe dispozitiv. După aceea totul funcționează fără internet.', 'Descarcă', 'Se descarcă…', 'Gata pentru offline', 'Setări', 'Limba interfeței', 'Automat', 'Citește traducerea cu voce tare', 'Vorbire lentă', 'Recunoaștere vocală', 'Rapidă', 'Precisă', 'Mod față în față', 'Șterge istoricul', 'Instalează aplicația', 'Atinge Partajează, apoi „Adaugă pe ecranul principal”', 'Deschide meniul browserului și atinge „Instalează aplicația”', 'Nu există voce pentru această limbă pe acest dispozitiv', 'Încă nu e descărcat — conectează-te o dată la internet și atinge Descarcă', 'Ceva n-a mers bine — încearcă din nou', 'Închide', 'Limba mea', 'Limba interlocutorului', 'Copiat', 'Se încarcă…'],
  cs: ['Překladač', 'Já', 'Protějšek', 'Klepněte na mikrofon a mluvte', 'Po stažení funguje bez internetu', 'Poslouchám…', 'Hotovo', 'Zrušit', 'Rozpoznávám…', 'Překládám…', 'Napište text…', 'Nebyla slyšet řeč — zkuste to znovu', 'Nerozuměl jsem — zopakujte to, prosím', 'Povolte přístup k mikrofonu', 'Stáhnout pro použití offline', 'Rozpoznávání řeči a překlad pro tuto dvojici jazyků se uloží do zařízení. Potom vše funguje bez internetu.', 'Stáhnout', 'Stahuje se…', 'Připraveno offline', 'Nastavení', 'Jazyk rozhraní', 'Automaticky', 'Přečíst překlad nahlas', 'Pomalá řeč', 'Rozpoznávání řeči', 'Rychlé', 'Přesné', 'Režim tváří v tvář', 'Vymazat historii', 'Nainstalujte aplikaci', 'Klepněte na Sdílet a pak na „Přidat na plochu“', 'Otevřete nabídku prohlížeče a klepněte na „Instalovat aplikaci“', 'Pro tento jazyk není v zařízení žádný hlas', 'Ještě není staženo — jednou se připojte k internetu a klepněte na Stáhnout', 'Něco se pokazilo — zkuste to znovu', 'Zavřít', 'Můj jazyk', 'Jazyk protějšku', 'Zkopírováno', 'Načítání…'],
  da: ['Oversætter', 'Mig', 'Samtalepartner', 'Tryk på mikrofonen og tal', 'Virker uden internet efter download', 'Lytter…', 'Færdig', 'Annuller', 'Genkender…', 'Oversætter…', 'Skriv tekst…', 'Ingen tale hørt — prøv igen', 'Forstod det ikke — gentag venligst', 'Tillad adgang til mikrofonen', 'Download til offlinebrug', 'Talegenkendelse og oversættelse for dette sprogpar gemmes på din enhed. Derefter virker alt uden internet.', 'Download', 'Downloader…', 'Klar offline', 'Indstillinger', 'Sprog i grænsefladen', 'Automatisk', 'Læs oversættelsen højt', 'Langsom tale', 'Talegenkendelse', 'Hurtig', 'Præcis', 'Ansigt til ansigt-tilstand', 'Ryd historik', 'Installer appen', 'Tryk på Del og derefter “Føj til hjemmeskærm”', 'Åbn browserens menu og tryk på “Installer app”', 'Ingen stemme til dette sprog på enheden', 'Ikke downloadet endnu — forbind til internettet én gang og tryk på Download', 'Noget gik galt — prøv igen', 'Luk', 'Mit sprog', 'Samtalepartnerens sprog', 'Kopieret', 'Indlæser…'],
  hu: ['Fordító', 'Én', 'Beszélgetőtárs', 'Koppints a mikrofonra és beszélj', 'Letöltés után internet nélkül működik', 'Figyelek…', 'Kész', 'Mégse', 'Felismerés…', 'Fordítás…', 'Írj szöveget…', 'Nem hallatszott beszéd — próbáld újra', 'Nem értettem — kérlek, ismételd meg', 'Engedélyezd a mikrofon használatát', 'Letöltés offline használatra', 'A beszédfelismerés és a fordítás ehhez a nyelvpárhoz az eszközödre kerül. Utána minden internet nélkül működik.', 'Letöltés', 'Letöltés folyamatban…', 'Offline használatra kész', 'Beállítások', 'Felület nyelve', 'Automatikus', 'Fordítás felolvasása', 'Lassú beszéd', 'Beszédfelismerés', 'Gyors', 'Pontos', 'Szemtől szembe mód', 'Előzmények törlése', 'Telepítsd az alkalmazást', 'Koppints a Megosztásra, majd a „Főképernyőhöz adás” lehetőségre', 'Nyisd meg a böngésző menüjét, és koppints az „Alkalmazás telepítése” lehetőségre', 'Ehhez a nyelvhez nincs hang ezen az eszközön', 'Még nincs letöltve — csatlakozz egyszer az internethez, és koppints a Letöltésre', 'Hiba történt — próbáld újra', 'Bezárás', 'Az én nyelvem', 'Beszélgetőtárs nyelve', 'Másolva', 'Betöltés…'],
  vi: ['Phiên dịch', 'Tôi', 'Người đối diện', 'Chạm vào micrô và nói', 'Hoạt động không cần mạng sau khi tải xuống', 'Đang nghe…', 'Xong', 'Hủy', 'Đang nhận dạng…', 'Đang dịch…', 'Nhập văn bản…', 'Không nghe thấy giọng nói — hãy thử lại', 'Chưa nghe rõ — vui lòng nói lại', 'Vui lòng cho phép truy cập micrô', 'Tải xuống để dùng ngoại tuyến', 'Nhận dạng giọng nói và bản dịch cho cặp ngôn ngữ này sẽ được lưu trên thiết bị. Sau đó mọi thứ hoạt động không cần mạng.', 'Tải xuống', 'Đang tải xuống…', 'Sẵn sàng ngoại tuyến', 'Cài đặt', 'Ngôn ngữ giao diện', 'Tự động', 'Đọc to bản dịch', 'Đọc chậm', 'Nhận dạng giọng nói', 'Nhanh', 'Chính xác', 'Chế độ đối diện', 'Xóa lịch sử', 'Cài đặt ứng dụng', 'Chạm Chia sẻ, rồi chọn “Thêm vào Màn hình chính”', 'Mở menu trình duyệt và chạm “Cài đặt ứng dụng”', 'Thiết bị này không có giọng đọc cho ngôn ngữ này', 'Chưa tải xuống — hãy kết nối mạng một lần và chạm Tải xuống', 'Đã xảy ra lỗi — hãy thử lại', 'Đóng', 'Ngôn ngữ của tôi', 'Ngôn ngữ của người đối diện', 'Đã sao chép', 'Đang tải…'],
  id: ['Penerjemah', 'Saya', 'Lawan bicara', 'Ketuk mikrofon lalu bicara', 'Berfungsi tanpa internet setelah diunduh', 'Mendengarkan…', 'Selesai', 'Batal', 'Mengenali…', 'Menerjemahkan…', 'Ketik teks…', 'Tidak ada suara terdengar — coba lagi', 'Kurang jelas — mohon ulangi', 'Izinkan akses mikrofon', 'Unduh untuk penggunaan offline', 'Pengenalan suara dan terjemahan untuk pasangan bahasa ini akan disimpan di perangkat Anda. Setelah itu semuanya berfungsi tanpa internet.', 'Unduh', 'Mengunduh…', 'Siap offline', 'Pengaturan', 'Bahasa antarmuka', 'Otomatis', 'Bacakan terjemahan', 'Bicara lambat', 'Pengenalan suara', 'Cepat', 'Akurat', 'Mode tatap muka', 'Hapus riwayat', 'Pasang aplikasi', 'Ketuk Bagikan, lalu “Tambah ke Layar Utama”', 'Buka menu browser dan ketuk “Instal aplikasi”', 'Tidak ada suara untuk bahasa ini di perangkat ini', 'Belum diunduh — sambungkan ke internet sekali lalu ketuk Unduh', 'Terjadi kesalahan — coba lagi', 'Tutup', 'Bahasa saya', 'Bahasa lawan bicara', 'Disalin', 'Memuat…'],
  th: ['นักแปล', 'ฉัน', 'คู่สนทนา', 'แตะไมโครโฟนแล้วพูด', 'ใช้งานได้โดยไม่ต้องใช้อินเทอร์เน็ตหลังดาวน์โหลด', 'กำลังฟัง…', 'เสร็จ', 'ยกเลิก', 'กำลังจดจำเสียง…', 'กำลังแปล…', 'พิมพ์ข้อความ…', 'ไม่ได้ยินเสียงพูด — ลองอีกครั้ง', 'ฟังไม่ชัด — กรุณาพูดอีกครั้ง', 'โปรดอนุญาตให้เข้าถึงไมโครโฟน', 'ดาวน์โหลดเพื่อใช้แบบออฟไลน์', 'ระบบจดจำเสียงและการแปลสำหรับคู่ภาษานี้จะถูกบันทึกไว้ในอุปกรณ์ของคุณ หลังจากนั้นทุกอย่างใช้ได้โดยไม่ต้องใช้อินเทอร์เน็ต', 'ดาวน์โหลด', 'กำลังดาวน์โหลด…', 'พร้อมใช้แบบออฟไลน์', 'การตั้งค่า', 'ภาษาของหน้าจอ', 'อัตโนมัติ', 'อ่านคำแปลออกเสียง', 'พูดช้า', 'การจดจำเสียง', 'เร็ว', 'แม่นยำ', 'โหมดหันหน้าเข้าหากัน', 'ล้างประวัติ', 'ติดตั้งแอป', 'แตะแชร์ แล้วเลือก “เพิ่มไปยังหน้าจอโฮม”', 'เปิดเมนูของเบราว์เซอร์แล้วแตะ “ติดตั้งแอป”', 'อุปกรณ์นี้ไม่มีเสียงสำหรับภาษานี้', 'ยังไม่ได้ดาวน์โหลด — เชื่อมต่ออินเทอร์เน็ตหนึ่งครั้งแล้วแตะดาวน์โหลด', 'เกิดข้อผิดพลาด — ลองอีกครั้ง', 'ปิด', 'ภาษาของฉัน', 'ภาษาของคู่สนทนา', 'คัดลอกแล้ว', 'กำลังโหลด…'],
  he: ['מתרגם', 'אני', 'בן/בת השיח', 'הקישו על המיקרופון ודברו', 'עובד בלי אינטרנט אחרי ההורדה', 'מקשיב…', 'סיום', 'ביטול', 'מזהה…', 'מתרגם…', 'הקלידו טקסט…', 'לא נשמע דיבור — נסו שוב', 'לא הבנתי — חזרו בבקשה', 'אנא אשרו גישה למיקרופון', 'הורדה לשימוש ללא חיבור', 'זיהוי הדיבור והתרגום עבור צמד השפות הזה יישמרו במכשיר. אחרי זה הכול עובד בלי אינטרנט.', 'הורדה', 'מוריד…', 'מוכן לשימוש ללא חיבור', 'הגדרות', 'שפת הממשק', 'אוטומטי', 'הקראת התרגום', 'דיבור איטי', 'זיהוי דיבור', 'מהיר', 'מדויק', 'מצב פנים אל פנים', 'ניקוי היסטוריה', 'התקינו את האפליקציה', 'הקישו על שיתוף ואז על „הוספה למסך הבית”', 'פתחו את תפריט הדפדפן והקישו על „התקנת אפליקציה”', 'אין קול לשפה הזו במכשיר הזה', 'עדיין לא הורד — התחברו לאינטרנט פעם אחת והקישו על הורדה', 'משהו השתבש — נסו שוב', 'סגירה', 'השפה שלי', 'השפה של בן/בת השיח', 'הועתק', 'טוען…'],
};

export const UI_LANGS = Object.keys(T);
export const RTL = new Set(['ar', 'he']);

let current = 'en';
let dict = {};

export function detectUiLang() {
  const prefs = navigator.languages && navigator.languages.length ? navigator.languages : [navigator.language || 'en'];
  for (const l of prefs) {
    let code = (l || '').toLowerCase().split('-')[0];
    if (code === 'iw') code = 'he';
    if (code === 'nb' || code === 'nn' || code === 'no') code = 'da';
    if (code === 'ms') code = 'id';
    if (T[code]) return code;
  }
  return 'en';
}

export function setUiLang(code) {
  current = T[code] ? code : 'en';
  dict = {};
  const vals = T[current];
  K.forEach((k, i) => { dict[k] = vals[i] ?? T.en[i]; });
  document.documentElement.lang = current;
  document.documentElement.dir = RTL.has(current) ? 'rtl' : 'ltr';
}

export function uiLang() {
  return current;
}

/** Текст на любом языке (для половины собеседника в режиме «лицом к лицу»). */
export function tIn(lang, key) {
  const vals = T[lang] || T.en;
  const i = K.indexOf(key);
  return (i >= 0 && vals[i]) || T.en[i] || key;
}

export function t(key) {
  return dict[key] ?? key;
}

/** Название языка на языке интерфейса (средствами самого телефона). */
export function langName(code, inLang = current) {
  try {
    const dn = new Intl.DisplayNames([inLang], { type: 'language' });
    const n = dn.of(code);
    return n ? n.charAt(0).toLocaleUpperCase(inLang) + n.slice(1) : code;
  } catch (_) {
    return code;
  }
}

/** Самоназвание языка (для списка языков интерфейса). */
export function nativeName(code) {
  return langName(code, code);
}

// Проверка целостности переводов (для самотеста)
export function checkI18n() {
  const bad = [];
  for (const [l, v] of Object.entries(T)) if (v.length !== K.length) bad.push(`${l}:${v.length}/${K.length}`);
  return bad;
}
